### ISSUE TITLE
flagship_get_posts_navigation

### ISSUE THREAD

**Issue by m-e-h** [FlagshipWP/flagship-library#10]
I'm not getting a class or id of 'nav-archive' on the pagination. 
Is the pagination wrapped in `hybrid_attr_nav` like the singular nav?

**Comment by robneu** [comment]
When using the pagination format it unfortunately is not. I wanted to use the WordPress core function and it's kind of limited. https://github.com/FlagshipWP/flagship-library/blob/master/functions/template-general.php#L339

The core function doesn't accept many arguments: http://codex.wordpress.org/Function_Reference/get_the_posts_pagination

I looked into passing more into the lower level function, but it doesn't accept much in terms of formatting either: https://github.com/WordPress/WordPress/blob/bfda508c18885bf30481a1a5f66ac45df1218e5e/wp-includes/general-template.php#L2741

I guess I could just have paginate_links return as an array and  then format it manually, but honestly that's probably what they should have done in core to allow for more flexibility in output. IMO the new core template tags kind of suck in general. :\

**Comment by m-e-h** [comment]
Oh OK. I missed that conditional in the filter. I see what's going on now.

And yeah, many of the new tags have really limited customization. I guess it's for the sake of 'consistency', which is an understandable goal. However, there's a fine line between consistency and monotony that needs to be watched out for.
