### ISSUE TITLE
Nofollow on the 'more' links

### ISSUE THREAD

**Issue by codepunk** [FlagshipWP/flagship-library#4]
Hi Rob,

What's the rationale for nofollowing the 'more' link to single posts?

Matt Cutts on nofollowing internal links - https://www.youtube.com/watch?v=86GHCVRReJs

**Comment by robneu** [comment]
They're used for crawl prioritization. My decision is based on years of experience, testing, and real-world applications. I don't really pay a whole lot of attention to what Matt Cutts says, so linking to his videos isn't going to help make your point. While it doesn't fully explain my rationale, this is directly from Google's own Webmaster Tools page:

> Crawl prioritization: Search engine robots can't sign in or register as a member on your forum, so there's no reason to invite Googlebot to follow "register here" or "sign in" links. Using nofollow on these links enables Googlebot to crawl other pages you'd prefer to see in Google's index. However, a solid information architecture — intuitive navigation, user- and search-engine-friendly URLs, and so on — is likely to be a far more productive use of resources than focusing on crawl prioritization via nofollowed links.

If you read between the lines, as is required with anything related to Google, you'll see that nofollowing links with a lower priority can help push value through to the links that you want Google to pay attention to. I'd much rather have Google prioritize my blog post titles, which are likely to contain keywords, than arbitrary "read more" text. If you disagree with my conclusions you're more than welcome to remove the filter.

**Comment by codepunk** [comment]
I disagree, but thanks for the explanation. 

I love the theme, particularly the highlighter plugin.

Cheers.

**Comment by robneu** [comment]
Glad to hear it! Please do open issues for anything else that you run into. While I might not always agree with everything, I will always at least re-consider my position on something when an issue is raised. :)
