### ISSUE TITLE
site_logo shows two Display Header Text checkboxes when using custom-header

### ISSUE THREAD

**Issue by m-e-h** [FlagshipWP/flagship-library#8]
`add_theme_support( 'custom-header' )` +  `add_theme_support( 'site-logo' )` = "Display Header Text" x 2
For me anyway..

**Comment by robneu** [comment]
We don't use custom headers in any of our themes, so I didn't include support for dealing with them. Is there a reason why you're using both?

**Comment by robneu** [comment]
This should be fixed now, but please reopen this if you run into any issues with the way I've worked around it.

**Comment by m-e-h** [comment]
Thanks so much Rob! I'll keep you posted if any issues pop up.
As to why I need both? Now that I think about it, I could probably accomplish the same thing with post images and customizer controls.
But basically I'm working on a multisite network for an organization that has several departments and entities within it. Some will be child themes with their own logos. Others will simply be sections or pages on the main website and share one logo but will still need to represent their own "brand" to their own audience. I was thinking Justin's Custom Headers plugin would be a good art direction solution for individual pages. 
I've just started integrating the Flagship Library because it includes some of the things I was already trying to do on my own. I'm working through things pretty quickly to see what all I can replace with it. I hope I don't get too annoying in the process. :grimacing:

**Comment by robneu** [comment]
Ah, that makes sense. I'm glad it's working out for you. :+1: 

Don't worry about being annoying, we're looking for as much feedback as possible right now so having someone using it for things outside of what we're normally doing is great.
