### ISSUE TITLE
Author Box settings aren't being saved in the admin

### ISSUE THREAD

**Issue by m-e-h** [FlagshipWP/flagship-library#9]
When I "Update Profile", my checkbox selections disappear.

**Comment by robneu** [comment]
I think this should be fixed on the develop branch now. Can you do me a favor pull in those template changes and make sure?

If all is good, I'll push a point release later today.

**Comment by m-e-h** [comment]
Yep. Working as it should now.

**Comment by robneu** [comment]
:+1: I'll get this fixed pushed into the master branch in a bit.

**Comment by robneu** [comment]
Fixed in 1.4.2!

**Comment by m-e-h** [comment]
:metal:
